spring:
  datasource:
    url: jdbc:mysql://49.4.94.24:3307/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 119900

  redis:
    database: 5
    host: 49.4.94.24
    password: Reconova_123456
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enable: true